name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2

      - run: flutter pub get
      - run: flutter build web --release --base-href=/

      - name: Add CNAME file
        run: echo "www.abdullahmuradportfolio.com" > build/web/CNAME
      - name: Deploy
        uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /